version: 2

updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
    ignore:
      - dependency-name: 'wasmparser'
      - dependency-name: 'wasmprinter'
      - dependency-name: 'wast'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      github-actions:
        patterns:
          - "*"
